---
title: 'Práctica 1: Web scraping'
author: "Miguel Santos Pérez  y Alejandro Arzola García"
date: "14 de abril de 2020"
output:
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: '2'
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '2'
subtitle: UOC - Tipología y ciclo de vida de los datos
toc-title: Índice
---

\newpage
# Contexto

# Componentes del grupo

* Miguel Santos Pérez (miguel8santos@uoc.edu)
* Alejandro Arzola García (aarzola@uoc.edu)

# Repositorio Github

Para la realización de esta práctica se ha creado un repositorio en _GitHub_ para trabajar de manera colaborativa y tener un control de versiones sobre el código fuente. Se puede acceder a este repositorio a través del siguiente enlace:

* https://github.com/aarzola-uoc/practica1-tycvd

# Título para el dataset

Euroliga 2019-2020. Marcadores y estadísticas.

# Descripción del dataset



# Representación gráfica

# Contenido

# Agradecimientos

# Inspiración

La creciente importancia de la explotación de los datos en el ámbito deportivo ha impactado de pleno en muchos deportes. Así, podemos ver como en el fútbol el Big Data es un elemento fundamental a la hora de diseñar campañas de marketing, fichar jugadores o preparar estrategias para partidos. En el baloncesto, es usado por todas las franquicias NBA y selecciones en los campeonatos continentales / mundiales. La inspiración de desarrollar este proyecto es un primer acercamiento a la extracción de datos para el baloncesto europeo de clubes, para su posterior análisis.

# Licencia

# Contribuciones al trabajo

**Contribuciones**              |  **Firma**                    | 
--------------------------------|:-----------------------------:|
Investigación previa            | MSP, AAG
Redacción de las respuestas     | MSP, AAG
Creación del repositorio GitHub | MSP, AAG
Desarrollo código               | MSP, AAG

